//Source code generated by AppGPT (www.appgpt.tech)
//to be autogenerated as template, one per resource
import { Entity, Column, PrimaryGeneratedColumn } from 'typeorm';

@Entity('Brands')
export class BrandsEntity {
  @PrimaryGeneratedColumn()
  id: number;

  @Column('text', { nullable: true })
  name: string;

  @Column('text', { nullable: true })
  logo: string;

  @Column('integer', { nullable: true })
  category: number;

  @Column('integer', { nullable: true })
  foundingYear: number;

  @Column('text', { nullable: true })
  currentStatus: string;
}
